version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/TechChallengeApp
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 300
     runas: root
  ApplicationStart:
    - location: /home/ubuntu/TechChallengeApp/dist/TechChallengeApp serve
      timeout: 300
      runas: ubuntu
